-- Generated by Oracle SQL Developer Data Modeler 3.3.0.734
--   at:        2013-04-03 19:58:30 CDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE student CASCADE 
;
DROP TABLE academic_info CASCADE 
;
DROP TABLE country CASCADE 
;
DROP TABLE immigration_info CASCADE 
;
DROP TABLE programs CASCADE 
;
DROP TABLE semester CASCADE 
;
DROP TABLE student_semester_relation CASCADE  
;
CREATE TABLE student 
    ( 
     ut_eid VARCHAR (10)  NOT NULL , 
     last_name VARCHAR (100) , 
     first_name VARCHAR (100) , 
     gender VARCHAR (1) , 
     marital_status VARCHAR (1) , 
     first_semester_enrolled INT , 
     last_semester_enrolled INT , 
     country_code INT , 
     flex1 DATE , 
     flex2 INT , 
     flex3 INT , 
     flex4 VARCHAR (100) , 
     flex5 VARCHAR (100) , 
     flex6 VARCHAR (100) , 
     PRIMARY KEY ( ut_eid ) 
    ) 
;

CREATE TABLE academic_info 
    ( 
     major_code INT  NOT NULL , 
     major_description VARCHAR (100) , 
     school_code INT , 
     school_name VARCHAR (200) , 
     flex1 DATE , 
     flex2 INT , 
     flex3 INT , 
     flex4 VARCHAR (100) , 
     flex5 VARCHAR (100) , 
     flex6 VARCHAR (100) ,
     PRIMARY KEY ( major_code )
    ) 
;



CREATE TABLE country 
    ( 
     country_code INT  NOT NULL , 
     country_name VARCHAR (100) , 
     Region_of_citizenship VARCHAR (50) , 
     region_code INT , 
     flex1 DATE , 
     flex2 INT , 
     flex3 INT , 
     flex4 VARCHAR (100) , 
     flex5 VARCHAR (100) , 
     flex6 VARCHAR (100) , 
     PRIMARY KEY ( country_code )
    ) 
;




CREATE TABLE immigration_info 
    ( 
     visa_status_code INT  NOT NULL , 
     visa_status_description VARCHAR (100) , 
     flex1 DATE , 
     flex2 INT , 
     flex3 INT , 
     flex4 VARCHAR (100) , 
     flex5 VARCHAR (100) , 
     flex6 VARCHAR (100) , 
     PRIMARY KEY ( visa_status_code )
    ) 
;


CREATE TABLE programs 
    ( 
     program_code INT  NOT NULL , 
     program_description VARCHAR (50) , 
     flex1 DATE , 
     flex2 INT , 
     flex3 INT , 
     flex4 VARCHAR (100) , 
     flex5 VARCHAR (100) , 
     flex6 VARCHAR (100) , 
     PRIMARY KEY ( program_code )
    ) 
;

CREATE TABLE semester 
    ( 
     semester VARCHAR (10)  NOT NULL , 
     year INT  NOT NULL , 
     ut_eid VARCHAR (10)  NOT NULL , 
     academic_level VARCHAR (2) , 
     classification VARCHAR (10) , 
     passport INT ,  
     program_code INT , 
     visa_status INT , 
     major_code INT , 
     major_code2 INT , 
     flex1 DATE , 
     flex2 INT , 
     flex3 INT , 
     flex4 VARCHAR (100) , 
     flex5 VARCHAR (100) , 
     flex6 VARCHAR (100) , 
     PRIMARY KEY ( semester, year, ut_eid )
    ) 
;


CREATE TABLE student_semester_relation 
    ( 
     student_ut_eid VARCHAR (10)  NOT NULL , 
     semester_semester VARCHAR (10)  NOT NULL , 
     semester_year INT  NOT NULL , 
     semester_ut_eid VARCHAR (10)  NOT NULL ,
     PRIMARY KEY ( student_ut_eid, semester_semester, semester_year, semester_ut_eid )
    ) 
;


ALTER TABLE student_semester_relation 
    ADD CONSTRAINT FK_ASS_5 FOREIGN KEY 
    ( 
     student_ut_eid
    ) 
    REFERENCES student 
    ( 
     ut_eid
    ) 
    ON DELETE CASCADE 
;


ALTER TABLE student_semester_relation 
    ADD CONSTRAINT FK_ASS_6 FOREIGN KEY 
    ( 
     semester_semester,
     semester_year,
     semester_ut_eid
    ) 
    REFERENCES semester 
    ( 
     semester,
     year,
     ut_eid
    ) 
;


ALTER TABLE semester 
    ADD CONSTRAINT program_semester_relation FOREIGN KEY 
    ( 
     program_code
    ) 
    REFERENCES programs 
    ( 
     program_code
    ) 
;


ALTER TABLE semester 
    ADD CONSTRAINT school2_semester_relation FOREIGN KEY 
    ( 
     major_code2
    ) 
    REFERENCES academic_info 
    ( 
     major_code
    ) 
;


ALTER TABLE semester 
    ADD CONSTRAINT school_semester_relation FOREIGN KEY 
    ( 
     major_code
    ) 
    REFERENCES academic_info 
    ( 
     major_code
    ) 
;


ALTER TABLE student 
    ADD CONSTRAINT student_country_relation FOREIGN KEY 
    ( 
     country_code
    ) 
    REFERENCES country 
    ( 
     country_code
    ) 
;


ALTER TABLE semester 
    ADD CONSTRAINT visa_semester_relation FOREIGN KEY 
    ( 
     visa_status
    ) 
    REFERENCES immigration_info 
    ( 
     visa_status_code
    ) 
;


INSERT INTO programs (program_code, program_description)
VALUES('1','regular');
INSERT INTO programs (program_code, program_description)
VALUES('2','scholars');
INSERT INTO programs (program_code, program_description)
VALUES('3','sponsored');
INSERT INTO programs (program_code, program_description)
VALUES('4','exchange');
INSERT INTO programs (program_code, program_description)
VALUES('5','both');


INSERT INTO immigration_info (visa_status_code, visa_status_description)
VALUES('0','default');

INSERT INTO country(country_code, country_name, region_of_citizenship, region_code)
VALUES('1', 'China', 'Asia', '1');
INSERT INTO country(country_code, country_name, region_of_citizenship, region_code)
VALUES('2', 'Mexico', 'North America', '2');
INSERT INTO country(country_code, country_name, region_of_citizenship, region_code)
VALUES('3', 'South Korea', 'Asia', '1');
INSERT INTO country(country_code, country_name, region_of_citizenship, region_code)
VALUES('4', 'France', 'Europe', '3');
INSERT INTO country(country_code, country_name, region_of_citizenship, region_code)
VALUES('5', 'Jamaica', 'Latin America and Caribbean', '3');
INSERT INTO country(country_code, country_name, region_of_citizenship, region_code)
VALUES('6', 'Guam', 'Oceana', '1');
INSERT INTO country(country_code, country_name, region_of_citizenship, region_code)
VALUES('7', 'Israel', 'Middle East', '4');
INSERT INTO country(country_code, country_name, region_of_citizenship, region_code)
VALUES('8', 'Jordan', 'Middle East', '4');
INSERT INTO country(country_code, country_name, region_of_citizenship, region_code)
VALUES('9', 'Lebanon', 'Middle East', '4');
INSERT INTO country(country_code, country_name, region_of_citizenship, region_code)
VALUES('10', 'Nigeria', 'Africa', '10');


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             14
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE STRUCTURED TYPE                   0
-- CREATE COLLECTION TYPE                   0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
